services:
  
  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8081:8080"

  discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8082:8080"
