services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    container_name: catalog-app-container
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    ports:
      - "8000:8080" 
    depends_on:
      - CatalogDB
      - Redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://CatalogDB:27017
      - MongoDbSettings__DatabaseName=CatalogDB
      - ConnectionStrings__Redis=Redis:6379

  CatalogDB:
    image: mongo:latest
    container_name: catalog-db-container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  Redis:
    image: redis:alpine
    container_name: catalog-redis-container
    ports:
      - "6379:6379"

volumes:
  mongo_data: